//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceePubCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chapter
    {
        public Chapter()
        {
            this.Favourite = new HashSet<Favourite>();
            this.eBook = new HashSet<eBook>();
        }
    
        public int id { get; private set; }
        public string title { get; set; }
        public int index { get; set; }
    
        public virtual ICollection<Favourite> Favourite { get; set; }
        public virtual ICollection<eBook> eBook { get; set; }
        public virtual Bookmark Bookmark { get; set; }
    }
}
