//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceePubCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class eBook
    {
        public eBook()
        {
            this.Favourite = new HashSet<Favourite>();
            this.Author = new HashSet<Author>();
            this.Genre = new HashSet<Genre>();
        }
    
        public int id { get; private set; }
        public string title { get; set; }
        public string folderPath { get; set; }
        public string imageUrl { get; set; }
    
        public virtual ICollection<Favourite> Favourite { get; set; }
        public virtual Chapter Chapter { get; set; }
        public virtual ICollection<Author> Author { get; set; }
        public virtual ICollection<Genre> Genre { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual Language Language { get; set; }
    }
}
