//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceePubCloud
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ePubBdModelContainer : DbContext
    {
        public ePubBdModelContainer()
            : base("name=ePubBdModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User> UserSet { get; set; }
        public DbSet<Genre> GenreSet { get; set; }
        public DbSet<Chapter> ChapterSet1 { get; set; }
        public DbSet<Bookmark> BookmarkSet { get; set; }
        public DbSet<Favourite> FavouriteSet { get; set; }
        public DbSet<Author> AuthorSet { get; set; }
        public DbSet<Publisher> PublisherSet { get; set; }
        public DbSet<eBook> eBookSet { get; set; }
        public DbSet<Gender> GenderSet { get; set; }
        public DbSet<Access> AccessSet { get; set; }
        public DbSet<Language> LanguageSet { get; set; }
    }
}
