//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePubIntegrator.ServiceePubCloudReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserContract", Namespace="http://schemas.datacontract.org/2004/07/ServiceePubCloud")]
    [System.SerializableAttribute()]
    public partial class UserContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LastLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LastLogin {
            get {
                return this.LastLoginField;
            }
            set {
                if ((this.LastLoginField.Equals(value) != true)) {
                    this.LastLoginField = value;
                    this.RaisePropertyChanged("LastLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EBookContract", Namespace="http://schemas.datacontract.org/2004/07/ServiceePubCloud")]
    [System.SerializableAttribute()]
    public partial class EBookContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolderPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FolderPath {
            get {
                return this.FolderPathField;
            }
            set {
                if ((object.ReferenceEquals(this.FolderPathField, value) != true)) {
                    this.FolderPathField = value;
                    this.RaisePropertyChanged("FolderPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUri {
            get {
                return this.ImageUriField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUriField, value) != true)) {
                    this.ImageUriField = value;
                    this.RaisePropertyChanged("ImageUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/ServiceePubCloud")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ePubIntegrator.ServiceePubCloudReference.Access[] AccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ePubIntegrator.ServiceePubCloudReference.Bookmark[] BookmarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ePubIntegrator.ServiceePubCloudReference.Favourite[] FavouriteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string genderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double lastLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ePubIntegrator.ServiceePubCloudReference.Access[] Access {
            get {
                return this.AccessField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessField, value) != true)) {
                    this.AccessField = value;
                    this.RaisePropertyChanged("Access");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ePubIntegrator.ServiceePubCloudReference.Bookmark[] Bookmark {
            get {
                return this.BookmarkField;
            }
            set {
                if ((object.ReferenceEquals(this.BookmarkField, value) != true)) {
                    this.BookmarkField = value;
                    this.RaisePropertyChanged("Bookmark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ePubIntegrator.ServiceePubCloudReference.Favourite[] Favourite {
            get {
                return this.FavouriteField;
            }
            set {
                if ((object.ReferenceEquals(this.FavouriteField, value) != true)) {
                    this.FavouriteField = value;
                    this.RaisePropertyChanged("Favourite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                if ((object.ReferenceEquals(this.genderField, value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lastLogin {
            get {
                return this.lastLoginField;
            }
            set {
                if ((this.lastLoginField.Equals(value) != true)) {
                    this.lastLoginField = value;
                    this.RaisePropertyChanged("lastLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Access", Namespace="http://schemas.datacontract.org/2004/07/ServiceePubCloud")]
    [System.SerializableAttribute()]
    public partial class Access : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ePubIntegrator.ServiceePubCloudReference.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ePubIntegrator.ServiceePubCloudReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bookmark", Namespace="http://schemas.datacontract.org/2004/07/ServiceePubCloud")]
    [System.SerializableAttribute()]
    public partial class Bookmark : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ePubIntegrator.ServiceePubCloudReference.Chapter ChapterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ePubIntegrator.ServiceePubCloudReference.User UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ePubIntegrator.ServiceePubCloudReference.Chapter Chapter {
            get {
                return this.ChapterField;
            }
            set {
                if ((object.ReferenceEquals(this.ChapterField, value) != true)) {
                    this.ChapterField = value;
                    this.RaisePropertyChanged("Chapter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ePubIntegrator.ServiceePubCloudReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Favourite", Namespace="http://schemas.datacontract.org/2004/07/ServiceePubCloud")]
    [System.SerializableAttribute()]
    public partial class Favourite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ePubIntegrator.ServiceePubCloudReference.Chapter ChapterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ePubIntegrator.ServiceePubCloudReference.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ePubIntegrator.ServiceePubCloudReference.eBook eBookField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ePubIntegrator.ServiceePubCloudReference.Chapter Chapter {
            get {
                return this.ChapterField;
            }
            set {
                if ((object.ReferenceEquals(this.ChapterField, value) != true)) {
                    this.ChapterField = value;
                    this.RaisePropertyChanged("Chapter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ePubIntegrator.ServiceePubCloudReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ePubIntegrator.ServiceePubCloudReference.eBook eBook {
            get {
                return this.eBookField;
            }
            set {
                if ((object.ReferenceEquals(this.eBookField, value) != true)) {
                    this.eBookField = value;
                    this.RaisePropertyChanged("eBook");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Chapter", Namespace="http://schemas.datacontract.org/2004/07/ServiceePubCloud")]
    [System.SerializableAttribute()]
    public partial class Chapter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ePubIntegrator.ServiceePubCloudReference.Bookmark BookmarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ePubIntegrator.ServiceePubCloudReference.Favourite[] FavouriteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ePubIntegrator.ServiceePubCloudReference.eBook[] eBookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int indexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ePubIntegrator.ServiceePubCloudReference.Bookmark Bookmark {
            get {
                return this.BookmarkField;
            }
            set {
                if ((object.ReferenceEquals(this.BookmarkField, value) != true)) {
                    this.BookmarkField = value;
                    this.RaisePropertyChanged("Bookmark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ePubIntegrator.ServiceePubCloudReference.Favourite[] Favourite {
            get {
                return this.FavouriteField;
            }
            set {
                if ((object.ReferenceEquals(this.FavouriteField, value) != true)) {
                    this.FavouriteField = value;
                    this.RaisePropertyChanged("Favourite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ePubIntegrator.ServiceePubCloudReference.eBook[] eBook {
            get {
                return this.eBookField;
            }
            set {
                if ((object.ReferenceEquals(this.eBookField, value) != true)) {
                    this.eBookField = value;
                    this.RaisePropertyChanged("eBook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int index {
            get {
                return this.indexField;
            }
            set {
                if ((this.indexField.Equals(value) != true)) {
                    this.indexField = value;
                    this.RaisePropertyChanged("index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eBook", Namespace="http://schemas.datacontract.org/2004/07/ServiceePubCloud")]
    [System.SerializableAttribute()]
    public partial class eBook : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ePubIntegrator.ServiceePubCloudReference.Author[] AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ePubIntegrator.ServiceePubCloudReference.Chapter ChapterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ePubIntegrator.ServiceePubCloudReference.Favourite[] FavouriteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ePubIntegrator.ServiceePubCloudReference.Genre[] GenreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ePubIntegrator.ServiceePubCloudReference.Language LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ePubIntegrator.ServiceePubCloudReference.Publisher PublisherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string folderPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ePubIntegrator.ServiceePubCloudReference.Author[] Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ePubIntegrator.ServiceePubCloudReference.Chapter Chapter {
            get {
                return this.ChapterField;
            }
            set {
                if ((object.ReferenceEquals(this.ChapterField, value) != true)) {
                    this.ChapterField = value;
                    this.RaisePropertyChanged("Chapter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ePubIntegrator.ServiceePubCloudReference.Favourite[] Favourite {
            get {
                return this.FavouriteField;
            }
            set {
                if ((object.ReferenceEquals(this.FavouriteField, value) != true)) {
                    this.FavouriteField = value;
                    this.RaisePropertyChanged("Favourite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ePubIntegrator.ServiceePubCloudReference.Genre[] Genre {
            get {
                return this.GenreField;
            }
            set {
                if ((object.ReferenceEquals(this.GenreField, value) != true)) {
                    this.GenreField = value;
                    this.RaisePropertyChanged("Genre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ePubIntegrator.ServiceePubCloudReference.Language Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ePubIntegrator.ServiceePubCloudReference.Publisher Publisher {
            get {
                return this.PublisherField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherField, value) != true)) {
                    this.PublisherField = value;
                    this.RaisePropertyChanged("Publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string folderPath {
            get {
                return this.folderPathField;
            }
            set {
                if ((object.ReferenceEquals(this.folderPathField, value) != true)) {
                    this.folderPathField = value;
                    this.RaisePropertyChanged("folderPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string imageUrl {
            get {
                return this.imageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.imageUrlField, value) != true)) {
                    this.imageUrlField = value;
                    this.RaisePropertyChanged("imageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Language", Namespace="http://schemas.datacontract.org/2004/07/ServiceePubCloud")]
    [System.SerializableAttribute()]
    public partial class Language : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ePubIntegrator.ServiceePubCloudReference.eBook[] eBookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ePubIntegrator.ServiceePubCloudReference.eBook[] eBook {
            get {
                return this.eBookField;
            }
            set {
                if ((object.ReferenceEquals(this.eBookField, value) != true)) {
                    this.eBookField = value;
                    this.RaisePropertyChanged("eBook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Publisher", Namespace="http://schemas.datacontract.org/2004/07/ServiceePubCloud")]
    [System.SerializableAttribute()]
    public partial class Publisher : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ePubIntegrator.ServiceePubCloudReference.eBook[] eBookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ePubIntegrator.ServiceePubCloudReference.eBook[] eBook {
            get {
                return this.eBookField;
            }
            set {
                if ((object.ReferenceEquals(this.eBookField, value) != true)) {
                    this.eBookField = value;
                    this.RaisePropertyChanged("eBook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Author", Namespace="http://schemas.datacontract.org/2004/07/ServiceePubCloud")]
    [System.SerializableAttribute()]
    public partial class Author : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ePubIntegrator.ServiceePubCloudReference.eBook[] eBookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ePubIntegrator.ServiceePubCloudReference.eBook[] eBook {
            get {
                return this.eBookField;
            }
            set {
                if ((object.ReferenceEquals(this.eBookField, value) != true)) {
                    this.eBookField = value;
                    this.RaisePropertyChanged("eBook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Genre", Namespace="http://schemas.datacontract.org/2004/07/ServiceePubCloud")]
    [System.SerializableAttribute()]
    public partial class Genre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ePubIntegrator.ServiceePubCloudReference.eBook[] eBookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ePubIntegrator.ServiceePubCloudReference.eBook[] eBook {
            get {
                return this.eBookField;
            }
            set {
                if ((object.ReferenceEquals(this.eBookField, value) != true)) {
                    this.eBookField = value;
                    this.RaisePropertyChanged("eBook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceePubCloudReference.IServiceePubCloud")]
    public interface IServiceePubCloud {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/GetServiceCurrentTime", ReplyAction="http://tempuri.org/IServiceePubCloud/GetServiceCurrentTimeResponse")]
        double GetServiceCurrentTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/GetServiceCurrentTime", ReplyAction="http://tempuri.org/IServiceePubCloud/GetServiceCurrentTimeResponse")]
        System.Threading.Tasks.Task<double> GetServiceCurrentTimeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/RegisterUser", ReplyAction="http://tempuri.org/IServiceePubCloud/RegisterUserResponse")]
        bool RegisterUser(ePubIntegrator.ServiceePubCloudReference.UserContract user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/RegisterUser", ReplyAction="http://tempuri.org/IServiceePubCloud/RegisterUserResponse")]
        System.Threading.Tasks.Task<bool> RegisterUserAsync(ePubIntegrator.ServiceePubCloudReference.UserContract user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/DeleteUser", ReplyAction="http://tempuri.org/IServiceePubCloud/DeleteUserResponse")]
        bool DeleteUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/DeleteUser", ReplyAction="http://tempuri.org/IServiceePubCloud/DeleteUserResponse")]
        System.Threading.Tasks.Task<bool> DeleteUserAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/Login", ReplyAction="http://tempuri.org/IServiceePubCloud/LoginResponse")]
        ePubIntegrator.ServiceePubCloudReference.UserContract Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/Login", ReplyAction="http://tempuri.org/IServiceePubCloud/LoginResponse")]
        System.Threading.Tasks.Task<ePubIntegrator.ServiceePubCloudReference.UserContract> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/CreateEbookRegistry", ReplyAction="http://tempuri.org/IServiceePubCloud/CreateEbookRegistryResponse")]
        bool CreateEbookRegistry(ePubIntegrator.ServiceePubCloudReference.EBookContract ebook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/CreateEbookRegistry", ReplyAction="http://tempuri.org/IServiceePubCloud/CreateEbookRegistryResponse")]
        System.Threading.Tasks.Task<bool> CreateEbookRegistryAsync(ePubIntegrator.ServiceePubCloudReference.EBookContract ebook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/DeleteEbookRegistry", ReplyAction="http://tempuri.org/IServiceePubCloud/DeleteEbookRegistryResponse")]
        bool DeleteEbookRegistry(string folderPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/DeleteEbookRegistry", ReplyAction="http://tempuri.org/IServiceePubCloud/DeleteEbookRegistryResponse")]
        System.Threading.Tasks.Task<bool> DeleteEbookRegistryAsync(string folderPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/CreateBookmark", ReplyAction="http://tempuri.org/IServiceePubCloud/CreateBookmarkResponse")]
        bool CreateBookmark(ePubIntegrator.ServiceePubCloudReference.User user, ePubIntegrator.ServiceePubCloudReference.Chapter chapter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/CreateBookmark", ReplyAction="http://tempuri.org/IServiceePubCloud/CreateBookmarkResponse")]
        System.Threading.Tasks.Task<bool> CreateBookmarkAsync(ePubIntegrator.ServiceePubCloudReference.User user, ePubIntegrator.ServiceePubCloudReference.Chapter chapter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/DeleteBookmark", ReplyAction="http://tempuri.org/IServiceePubCloud/DeleteBookmarkResponse")]
        bool DeleteBookmark(ePubIntegrator.ServiceePubCloudReference.User user, ePubIntegrator.ServiceePubCloudReference.Chapter chapter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/DeleteBookmark", ReplyAction="http://tempuri.org/IServiceePubCloud/DeleteBookmarkResponse")]
        System.Threading.Tasks.Task<bool> DeleteBookmarkAsync(ePubIntegrator.ServiceePubCloudReference.User user, ePubIntegrator.ServiceePubCloudReference.Chapter chapter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/CreateFavouriteChapter", ReplyAction="http://tempuri.org/IServiceePubCloud/CreateFavouriteChapterResponse")]
        bool CreateFavouriteChapter(ePubIntegrator.ServiceePubCloudReference.User user, ePubIntegrator.ServiceePubCloudReference.Chapter chapter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/CreateFavouriteChapter", ReplyAction="http://tempuri.org/IServiceePubCloud/CreateFavouriteChapterResponse")]
        System.Threading.Tasks.Task<bool> CreateFavouriteChapterAsync(ePubIntegrator.ServiceePubCloudReference.User user, ePubIntegrator.ServiceePubCloudReference.Chapter chapter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/DeleteFavouriteChapter", ReplyAction="http://tempuri.org/IServiceePubCloud/DeleteFavouriteChapterResponse")]
        bool DeleteFavouriteChapter(ePubIntegrator.ServiceePubCloudReference.User user, ePubIntegrator.ServiceePubCloudReference.Chapter chapter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/DeleteFavouriteChapter", ReplyAction="http://tempuri.org/IServiceePubCloud/DeleteFavouriteChapterResponse")]
        System.Threading.Tasks.Task<bool> DeleteFavouriteChapterAsync(ePubIntegrator.ServiceePubCloudReference.User user, ePubIntegrator.ServiceePubCloudReference.Chapter chapter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/CreateFavouriteEbook", ReplyAction="http://tempuri.org/IServiceePubCloud/CreateFavouriteEbookResponse")]
        bool CreateFavouriteEbook(ePubIntegrator.ServiceePubCloudReference.User user, ePubIntegrator.ServiceePubCloudReference.eBook eBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/CreateFavouriteEbook", ReplyAction="http://tempuri.org/IServiceePubCloud/CreateFavouriteEbookResponse")]
        System.Threading.Tasks.Task<bool> CreateFavouriteEbookAsync(ePubIntegrator.ServiceePubCloudReference.User user, ePubIntegrator.ServiceePubCloudReference.eBook eBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/DeleteFavouriteEbook", ReplyAction="http://tempuri.org/IServiceePubCloud/DeleteFavouriteEbookResponse")]
        bool DeleteFavouriteEbook(ePubIntegrator.ServiceePubCloudReference.User user, ePubIntegrator.ServiceePubCloudReference.eBook eBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/DeleteFavouriteEbook", ReplyAction="http://tempuri.org/IServiceePubCloud/DeleteFavouriteEbookResponse")]
        System.Threading.Tasks.Task<bool> DeleteFavouriteEbookAsync(ePubIntegrator.ServiceePubCloudReference.User user, ePubIntegrator.ServiceePubCloudReference.eBook eBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/CreateAuthor", ReplyAction="http://tempuri.org/IServiceePubCloud/CreateAuthorResponse")]
        bool CreateAuthor(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/CreateAuthor", ReplyAction="http://tempuri.org/IServiceePubCloud/CreateAuthorResponse")]
        System.Threading.Tasks.Task<bool> CreateAuthorAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/DeleteAuthor", ReplyAction="http://tempuri.org/IServiceePubCloud/DeleteAuthorResponse")]
        bool DeleteAuthor(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/DeleteAuthor", ReplyAction="http://tempuri.org/IServiceePubCloud/DeleteAuthorResponse")]
        System.Threading.Tasks.Task<bool> DeleteAuthorAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/CreatePublisher", ReplyAction="http://tempuri.org/IServiceePubCloud/CreatePublisherResponse")]
        bool CreatePublisher(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/CreatePublisher", ReplyAction="http://tempuri.org/IServiceePubCloud/CreatePublisherResponse")]
        System.Threading.Tasks.Task<bool> CreatePublisherAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/DeletePublisher", ReplyAction="http://tempuri.org/IServiceePubCloud/DeletePublisherResponse")]
        bool DeletePublisher(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/DeletePublisher", ReplyAction="http://tempuri.org/IServiceePubCloud/DeletePublisherResponse")]
        System.Threading.Tasks.Task<bool> DeletePublisherAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/CreateLanguage", ReplyAction="http://tempuri.org/IServiceePubCloud/CreateLanguageResponse")]
        bool CreateLanguage(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/CreateLanguage", ReplyAction="http://tempuri.org/IServiceePubCloud/CreateLanguageResponse")]
        System.Threading.Tasks.Task<bool> CreateLanguageAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/DeleteLanguage", ReplyAction="http://tempuri.org/IServiceePubCloud/DeleteLanguageResponse")]
        bool DeleteLanguage(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/DeleteLanguage", ReplyAction="http://tempuri.org/IServiceePubCloud/DeleteLanguageResponse")]
        System.Threading.Tasks.Task<bool> DeleteLanguageAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/CreateAccess", ReplyAction="http://tempuri.org/IServiceePubCloud/CreateAccessResponse")]
        bool CreateAccess(ePubIntegrator.ServiceePubCloudReference.User user, short type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceePubCloud/CreateAccess", ReplyAction="http://tempuri.org/IServiceePubCloud/CreateAccessResponse")]
        System.Threading.Tasks.Task<bool> CreateAccessAsync(ePubIntegrator.ServiceePubCloudReference.User user, short type);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceePubCloudChannel : ePubIntegrator.ServiceePubCloudReference.IServiceePubCloud, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceePubCloudClient : System.ServiceModel.ClientBase<ePubIntegrator.ServiceePubCloudReference.IServiceePubCloud>, ePubIntegrator.ServiceePubCloudReference.IServiceePubCloud {
        
        public ServiceePubCloudClient() {
        }
        
        public ServiceePubCloudClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceePubCloudClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceePubCloudClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceePubCloudClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double GetServiceCurrentTime() {
            return base.Channel.GetServiceCurrentTime();
        }
        
        public System.Threading.Tasks.Task<double> GetServiceCurrentTimeAsync() {
            return base.Channel.GetServiceCurrentTimeAsync();
        }
        
        public bool RegisterUser(ePubIntegrator.ServiceePubCloudReference.UserContract user) {
            return base.Channel.RegisterUser(user);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterUserAsync(ePubIntegrator.ServiceePubCloudReference.UserContract user) {
            return base.Channel.RegisterUserAsync(user);
        }
        
        public bool DeleteUser(string username) {
            return base.Channel.DeleteUser(username);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteUserAsync(string username) {
            return base.Channel.DeleteUserAsync(username);
        }
        
        public ePubIntegrator.ServiceePubCloudReference.UserContract Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<ePubIntegrator.ServiceePubCloudReference.UserContract> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public bool CreateEbookRegistry(ePubIntegrator.ServiceePubCloudReference.EBookContract ebook) {
            return base.Channel.CreateEbookRegistry(ebook);
        }
        
        public System.Threading.Tasks.Task<bool> CreateEbookRegistryAsync(ePubIntegrator.ServiceePubCloudReference.EBookContract ebook) {
            return base.Channel.CreateEbookRegistryAsync(ebook);
        }
        
        public bool DeleteEbookRegistry(string folderPath) {
            return base.Channel.DeleteEbookRegistry(folderPath);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteEbookRegistryAsync(string folderPath) {
            return base.Channel.DeleteEbookRegistryAsync(folderPath);
        }
        
        public bool CreateBookmark(ePubIntegrator.ServiceePubCloudReference.User user, ePubIntegrator.ServiceePubCloudReference.Chapter chapter) {
            return base.Channel.CreateBookmark(user, chapter);
        }
        
        public System.Threading.Tasks.Task<bool> CreateBookmarkAsync(ePubIntegrator.ServiceePubCloudReference.User user, ePubIntegrator.ServiceePubCloudReference.Chapter chapter) {
            return base.Channel.CreateBookmarkAsync(user, chapter);
        }
        
        public bool DeleteBookmark(ePubIntegrator.ServiceePubCloudReference.User user, ePubIntegrator.ServiceePubCloudReference.Chapter chapter) {
            return base.Channel.DeleteBookmark(user, chapter);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteBookmarkAsync(ePubIntegrator.ServiceePubCloudReference.User user, ePubIntegrator.ServiceePubCloudReference.Chapter chapter) {
            return base.Channel.DeleteBookmarkAsync(user, chapter);
        }
        
        public bool CreateFavouriteChapter(ePubIntegrator.ServiceePubCloudReference.User user, ePubIntegrator.ServiceePubCloudReference.Chapter chapter) {
            return base.Channel.CreateFavouriteChapter(user, chapter);
        }
        
        public System.Threading.Tasks.Task<bool> CreateFavouriteChapterAsync(ePubIntegrator.ServiceePubCloudReference.User user, ePubIntegrator.ServiceePubCloudReference.Chapter chapter) {
            return base.Channel.CreateFavouriteChapterAsync(user, chapter);
        }
        
        public bool DeleteFavouriteChapter(ePubIntegrator.ServiceePubCloudReference.User user, ePubIntegrator.ServiceePubCloudReference.Chapter chapter) {
            return base.Channel.DeleteFavouriteChapter(user, chapter);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteFavouriteChapterAsync(ePubIntegrator.ServiceePubCloudReference.User user, ePubIntegrator.ServiceePubCloudReference.Chapter chapter) {
            return base.Channel.DeleteFavouriteChapterAsync(user, chapter);
        }
        
        public bool CreateFavouriteEbook(ePubIntegrator.ServiceePubCloudReference.User user, ePubIntegrator.ServiceePubCloudReference.eBook eBook) {
            return base.Channel.CreateFavouriteEbook(user, eBook);
        }
        
        public System.Threading.Tasks.Task<bool> CreateFavouriteEbookAsync(ePubIntegrator.ServiceePubCloudReference.User user, ePubIntegrator.ServiceePubCloudReference.eBook eBook) {
            return base.Channel.CreateFavouriteEbookAsync(user, eBook);
        }
        
        public bool DeleteFavouriteEbook(ePubIntegrator.ServiceePubCloudReference.User user, ePubIntegrator.ServiceePubCloudReference.eBook eBook) {
            return base.Channel.DeleteFavouriteEbook(user, eBook);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteFavouriteEbookAsync(ePubIntegrator.ServiceePubCloudReference.User user, ePubIntegrator.ServiceePubCloudReference.eBook eBook) {
            return base.Channel.DeleteFavouriteEbookAsync(user, eBook);
        }
        
        public bool CreateAuthor(string name) {
            return base.Channel.CreateAuthor(name);
        }
        
        public System.Threading.Tasks.Task<bool> CreateAuthorAsync(string name) {
            return base.Channel.CreateAuthorAsync(name);
        }
        
        public bool DeleteAuthor(string name) {
            return base.Channel.DeleteAuthor(name);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAuthorAsync(string name) {
            return base.Channel.DeleteAuthorAsync(name);
        }
        
        public bool CreatePublisher(string name) {
            return base.Channel.CreatePublisher(name);
        }
        
        public System.Threading.Tasks.Task<bool> CreatePublisherAsync(string name) {
            return base.Channel.CreatePublisherAsync(name);
        }
        
        public bool DeletePublisher(string name) {
            return base.Channel.DeletePublisher(name);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePublisherAsync(string name) {
            return base.Channel.DeletePublisherAsync(name);
        }
        
        public bool CreateLanguage(string name) {
            return base.Channel.CreateLanguage(name);
        }
        
        public System.Threading.Tasks.Task<bool> CreateLanguageAsync(string name) {
            return base.Channel.CreateLanguageAsync(name);
        }
        
        public bool DeleteLanguage(string name) {
            return base.Channel.DeleteLanguage(name);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteLanguageAsync(string name) {
            return base.Channel.DeleteLanguageAsync(name);
        }
        
        public bool CreateAccess(ePubIntegrator.ServiceePubCloudReference.User user, short type) {
            return base.Channel.CreateAccess(user, type);
        }
        
        public System.Threading.Tasks.Task<bool> CreateAccessAsync(ePubIntegrator.ServiceePubCloudReference.User user, short type) {
            return base.Channel.CreateAccessAsync(user, type);
        }
    }
}
