//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePubIntegrator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ePubIntegrator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;paths&gt;
        ///  &lt;xml-path-config&gt;&lt;/xml-path-config&gt;
        ///  &lt;xml-path-gallery&gt;&lt;/xml-path-gallery&gt;
        ///&lt;/paths&gt;.
        /// </summary>
        internal static string appconfig {
            get {
                return ResourceManager.GetString("appconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..//Debug//appconfig.xml.
        /// </summary>
        internal static string AppConfigPath {
            get {
                return ResourceManager.GetString("AppConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default configuration file was not found.
        ///Generating a new one..
        /// </summary>
        internal static string DefaultCfgNotFound {
            get {
                return ResourceManager.GetString("DefaultCfgNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//config//epubConfigurations.xml.
        /// </summary>
        internal static string DefaultConfigXmlFilePath {
            get {
                return ResourceManager.GetString("DefaultConfigXmlFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//config//epubConfigurationsSchema.xsd.
        /// </summary>
        internal static string DefaultConfigXsdFilePath {
            get {
                return ResourceManager.GetString("DefaultConfigXsdFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:54317/ServiceePubCloud.svc.
        /// </summary>
        internal static string DefaultEndpoint {
            get {
                return ResourceManager.GetString("DefaultEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default configuration.
        /// </summary>
        internal static string DefaultFileTypeConfig {
            get {
                return ResourceManager.GetString("DefaultFileTypeConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default gallery file was not found.
        ///Generating a new one..
        /// </summary>
        internal static string DefaultGalleryDataNotFound {
            get {
                return ResourceManager.GetString("DefaultGalleryDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//config//epubLocalData.xml.
        /// </summary>
        internal static string DefaultGalleryDataXmlFilePath {
            get {
                return ResourceManager.GetString("DefaultGalleryDataXmlFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//config//epubLocalDataSchema.xsd.
        /// </summary>
        internal static string DefaultGalleryDataXsdFilePath {
            get {
                return ResourceManager.GetString("DefaultGalleryDataXsdFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//gallery//.
        /// </summary>
        internal static string DefaultGalleryPath {
            get {
                return ResourceManager.GetString("DefaultGalleryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\eBooks\\.
        /// </summary>
        internal static string eBookFolderPath {
            get {
                return ResourceManager.GetString("eBookFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .epub.
        /// </summary>
        internal static string epubFileExtenstion {
            get {
                return ResourceManager.GetString("epubFileExtenstion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and Password Required.
        /// </summary>
        internal static string ErrorAuthFieldsRequired {
            get {
                return ResourceManager.GetString("ErrorAuthFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist or invalid username/password combination.
        /// </summary>
        internal static string ErrorAuthText {
            get {
                return ResourceManager.GetString("ErrorAuthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every field is required to register.
        /// </summary>
        internal static string ErrorRegisterFields {
            get {
                return ResourceManager.GetString("ErrorRegisterFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username is already in use. Please try again..
        /// </summary>
        internal static string ErrorRegistration {
            get {
                return ResourceManager.GetString("ErrorRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configuration.
        /// </summary>
        internal static string FileTypeConfig {
            get {
                return ResourceManager.GetString("FileTypeConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gallery.
        /// </summary>
        internal static string FileTypeData {
            get {
                return ResourceManager.GetString("FileTypeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_book {
            get {
                object obj = ResourceManager.GetObject("ico_book", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_book_active {
            get {
                object obj = ResourceManager.GetObject("ico_book_active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_book_fav {
            get {
                object obj = ResourceManager.GetObject("ico_book_fav", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_book_fav_active {
            get {
                object obj = ResourceManager.GetObject("ico_book_fav_active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_fav {
            get {
                object obj = ResourceManager.GetObject("ico_fav", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_left_arrow {
            get {
                object obj = ResourceManager.GetObject("ico_left_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_right_arrow {
            get {
                object obj = ResourceManager.GetObject("ico_right_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file path specified in the application does not contain a configuration file. Should the application attempt to find it in the default path?.
        /// </summary>
        internal static string UserDefinedCfgNotFound {
            get {
                return ResourceManager.GetString("UserDefinedCfgNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file path specified in the application does not contain a gallery data file. Should the application attempt to find it in the default path?.
        /// </summary>
        internal static string UserDefinedGalleryDataNotFound {
            get {
                return ResourceManager.GetString("UserDefinedGalleryDataNotFound", resourceCulture);
            }
        }
    }
}
